onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bigint-buffer
  - bufferutil
  - core-js
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
